name: 'motorsport_dbt'
version: '1.0.0'
config-version: 2

profile: 'motorsport'

require-dbt-version: [">=1.8.0", "<2.0.0"]

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  motorsport_dbt:
    gold:
      +materialized: table
      +schema: gold