FROM confluentinc/cp-kafka-connect:7.7.0

USER root
RUN microdnf install -y jq unzip \
 && curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip \
 && unzip -q /tmp/awscliv2.zip -d /tmp \
 && /tmp/aws/install \
 && rm -rf /tmp/aws /tmp/awscliv2.zip \
 && microdnf clean all
USER appuser

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest

COPY debezium/connect-entrypoint.sh /connect-entrypoint.sh
ENTRYPOINT ["/bin/bash", "/connect-entrypoint.sh"]