services:
  # app is for local development only
  #app:
  #  build: .
  #  env_file:
  #    - .env
  #  volumes:
  #    - .:/app

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports: []
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
  
  kafka-connect:
    image: debezium/connect:latest
    container_name: kafka-connect
    depends_on:
      - kafka
    ports: []
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: motorsport-connect-cluster
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
    restart: unless-stopped
    
volumes:
  kafka-data: