services:
  # app is for local development only
  app:
    build: .
    #env_file:
    #  - .env
    #volumes:
    #  - .:/app
    environment:
      AWS_DEFAULT_REGION: us-east-2
    command: tail -f /dev/null

  init-connector:
    build:
      context: .
      dockerfile: dockerfile.init
    container_name: init-connector
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./debezium:/debezium:ro
      - ./db:/db:ro
    entrypoint: ["/bin/bash", "/debezium/init-connector.sh"]
    restart: "no"
  
  kafka-connect:
    build:
      context: .
      dockerfile: dockerfile.connect
    container_name: kafka-connect
    ports: []
    environment:
      AWS_REGION: us-east-2
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_ADMIN_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_ADMIN_SASL_MECHANISM: PLAIN
      CONNECT_GROUP_ID: motorsport-connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/connectors"]
      interval: 10s
      timeout: 10s
      retries: 18
      start_period: 30s