select
    vehicle_id,
    owner_id as driver_id,
    make as vehicle_make,
    model as vehicle_model,
    horsepower,
    torque,
    redline as redline_rpm,
    engine_layout,
    engine_cylinders,
    engine_displacement,
    force_induction,
    boost_pressure,
    gearbox_type,
    gear_count,
    drivetrain,
    length as vehicle_length,
    width as vehicle_width,
    height as vehicle_height,
    wheelbase as vehicle_wheelbase,
    wheel_diameter,
    wheel_width,
    wheel_weight,
    curb_weight,
    tires
from {{ source('silver', 'vehicles') }}