LOG_HZ = 20
LIVE_HZ = 5

LIVE_FIELDS = [
    "session_id",
    "timestamp",
    "throttle_position",
    "brake_position",
    "toe_angle",
    "steering_wheel_angle",
    "gear_position",
    "rpm",
    "speed",
    "brake_pressure",
    "engine_oil_pressure",
    "engine_oil_temperature",
    "manifold_air_pressure",
    "exhaust_gas_temperature",
    "knock_sensor",
    "lambda_sensor",
    "boost_pressure",
    "fuel_pressure",
    "fuel_flow",
    "fuel_level",
    "coolant_temperature",
    "transmission_fluid_temperature",
    "battery_voltage",
    "battery_temperature",
    "g_force_longitude",
    "g_force_latitude",
    "g_force_lateral",
    "latitude",
    "longitude",
    "fl_wheel_speed",
    "fl_shock_travel",
    "fl_ride_height",
    "fl_tire_pressure",
    "fr_wheel_speed",
    "fr_shock_travel",
    "fr_ride_height",
    "fr_tire_pressure",
    "rl_wheel_speed",
    "rl_shock_travel",
    "rl_tire_pressure",
    "rl_ride_height",
    "rr_wheel_speed",
    "rr_shock_travel",
    "rr_ride_height",
    "rr_tire_pressure",
    "driver_heart_rate",
    "driver_blood_oxygen",
    "driver_core_body_temperature",
    "driver_respiratory_rate",
]
 
LOG_FIELDS = [
    "session_id",
    "timestamp",
    "throttle_position",
    "brake_position",
    "toe_angle",
    "steering_wheel_angle",
    "steering_torque",
    "gear_position",
    "rpm",
    "speed",
    "brake_pressure",
    "driveshaft_rpm",
    "engine_oil_pressure",
    "engine_oil_temperature",
    "manifold_air_pressure",
    "manifold_air_temperature",
    "exhaust_gas_temperature",
    "cam_position",
    "crank_position",
    "knock_sensor",
    "lambda_sensor",
    "boost_pressure",
    "wastegate_position",
    "fuel_pressure",
    "fuel_flow",
    "fuel_level",
    "coolant_temperature",
    "transmission_fluid_temperature",
    "battery_voltage",
    "battery_temperature",
    "alternator_output",
    "g_force_longitude",
    "g_force_latitude",
    "g_force_lateral",
    "latitude",
    "longitude",
    "fl_wheel_speed",
    "fl_wheel_load",
    "fl_shock_travel",
    "fl_ride_height",
    "fl_tire_pressure",
    "fl_brake_temperature",
    "fl_tire_temperature",
    "fr_wheel_speed",
    "fr_wheel_load",
    "fr_shock_travel",
    "fr_ride_height",
    "fr_tire_pressure",
    "fr_tire_temperature",
    "fr_brake_temperature",
    "rl_wheel_speed",
    "rl_wheel_load",
    "rl_shock_travel",
    "rl_tire_pressure",
    "rl_ride_height",
    "rl_tire_temperature",
    "rl_brake_temperature",
    "rr_wheel_speed",
    "rr_wheel_load",
    "rr_shock_travel",
    "rr_ride_height",
    "rr_tire_pressure",
    "rr_tire_temperature",
    "rr_brake_temperature",
    "driver_heart_rate",
    "driver_blood_oxygen",
    "driver_core_body_temperature",
    "driver_respiratory_rate",
    "pitot_tube",
    "pressure_tap_front_wing",
    "pressure_tap_rear_wing",
    "pressure_tap_diffuser",
    "pressure_tap_splitter",
    "kiel_probe_front_wing",
    "kiel_probe_rear_wing",
    "kiel_probe_diffuser",
    "strain_rollcage",
    "strain_subframe",
    "strain_fl_suspension",
    "strain_fr_suspension",
    "strain_rl_suspension",
    "strain_rr_suspension",
]

DRIVER_FIELDS= []

TRACK_SUFFIXES = ["Speedway", "Raceway", "Circuit", "International Raceway", "Motorplex", "Grand Prix Course"]

ENGINE_LAYOUT = ["Inline","V","Boxer"]
FORCE_INDUCTION = ["Turbo","Supercharger","NA","Twin-Charged"]
GEARBOX_TYPE = ["Manual","Automatic","Sequential"]
DRIVETRAINS = ["FWD","RWD","AWD"]
TURN_TYPE = ["Hairpin","Carousel","Chicane","Corkscrew","Esses","Double Apex","Kink","Sweeper","90-Degree","Spoon","Snail"]